/* 
 * @Author: yz.yujingzhou 
 * @Date: 2020-11-27 18:22:39 
 * @Last Modified by: yangyiting
 * @Last Modified time: 2021-03-24 17:45:27
 */

part of '../action.dart';

/// Storing all system handlers for register
/// 存放系统所有action的地方，注册的时候从这里取，看 commom.dart 里的 【reginsterPageExitHandler】
List<YZDynamicActionHandler> yzAllDynamicExitHandlers = [
     
  //router   
  YZRouterPopHandler(),

  //List
  YZListHandler(),
  YZListValueOfIndexHandler(),
  YZListGenerateHandler(),
  YZListIsEmptyHandler(),
  YZListIsNotEmptyHandler(),
  YZListLengthHandler(),
  YZListClearHandler(),
  YZListFirstHandler(),
  YZListLastHandler(),
  YZListAddHandler(),
  YZListAddAllHandler(),
  YZListIndexOfHandler(),
  YZListLastIndexOfHandler(),
  YZListInsertHandler(),
  YZListInsertAllHandler(),
  YZListSetAllHandler(),
  YZListRemoveHandler(),
  YZListRemoveAtHandler(),
  YZListRemoveLastHandler(),
  YZListSublistHandler(),
  YZListAsMapHandler(),
  YZListReplaceRangeHandler(),
  YZListFillRangeHandler(),
  YZListRemoveRangeHandler(),
  YZListSetRangeHandler(),
  YZListGetRangeHandler(),
  YZListShuffleHandler(),
  YZListCopyRangeHandler(),
  YZListUnmodifiableHandler(),
  YZListFromHandler(),
  YZListOfHandler(),
  YZListFollowedByHandler(),
  YZListContainsHandler(),
  YZListJoinHandler(),
  YZListToSetHandler(),
  YZListTakeHandler(),
  YZListSkipHandler(),
  YZListElementAtHandler(),
  YZListToStringHandler(),

  //String
  YZStringHandler(),
  YZStringIsEmptyHandler(),   
  YZStringIsNotEmptyHandler(),
  YZStringPlusHandler(),
  YZStringLengthHandler(),
  YZStringCompareToHandler(),
  YZStringIndexOfHandler(),
  YZStringLastIndexOfHandler(),
  YZStringContainsHandler(),
  YZStringEndsWithHandler(),
  YZStringStartsWithHandler(),
  YZStringPadLeftHandler(),
  YZStringPadRightHandler(),
  YZStringReplaceAllHandler(),
  YZStringReplaceFirstHandler(),
  YZStringReplaceRangeHandler(),
  YZStringSubstringHandler(),
  YZStringToLowerCaseHandler(),
  YZStringToUpperCaseHandler(),
  YZStringTrimHandler(),
  YZStringTrimLeftHandler(),
  YZStringTrimRightHandler(),
  YZStringSplitHandler(), 
  YZStringAllMatchesHandler(),
  YZStringMatchAsPrefix(), 

  //RegExp
  YZRegExpHasMatchHandler(),  

  //Number
  YZIntHandler(),
  YZDoubleHandler(),
  YZNumHandler(),  
  YZPlusHandler(),
  YZMultiHandler(),
  YZSubHandler(),
  YZDivHandler(),
  YZRemainderHandler(),
  YZPlusEqualHandler(),
  YZSubEqualHandler(),
  YZMultiEqualHandler(),
  YZDivEqualHandler(),
  YZParseHandler(),
  YZTryParseHandler(),
  YZIsNaNHandler(),
  YZIsInfiniteHandler(),
  YZIsFiniteHandler(),
  YZIsNegativeHandler(),
  YZAbsHandler(),
  YZClampHandler(),
  YZCeilHandler(),
  YZCeilToDoubleHandler(),
  YZCompareToHandler(),
  YZFloorHandler(),
  YZFloorToDoubleHandler(),
  YZRoundHandler(),
  YZRoundToDoubleHandler(),
  YZToDoubleHandler(),
  YZToIntHandler(),
  YZTruncateHandler(),
  YZTruncateToDoubleHandler(),
  YZToStringHandler(),
  YZToStringAsExponentialHandler(),
  YZToStringAsFixedHandler(),
  YZToStringAsPrecisionHandler(),  

  //Map
  YZMapHandler(),
  YZMapEntryHandler(),
  YZMapValueOfKeyHandler(),
  YZMapIsEmptyHandler(),
  YZMapIsNotEmptyHandler(),
  YZMapLengthHandler(),
  YZMapContainsValueHandler(),
  YZMapContainsKeyHandler(),
  YZMapRemoveKeyHandler(),
  YZMapClearHandler(),
  YZMapKeysHandler(),
  YZMapValuesHandler(),
  YZMapEntriesHandler(),
  YZMapAddAllHandler(),
  YZMapAddEntriesHandler(),
  YZMapToStringHandler(),
  YZMapFromHandler(),
  YZMapOfHandler(),
  YZMapIdentityHandler(),
  YZMapFromEntriesHandler(),
  YZMapFromIterableHandler(),
  YZMapFromIterablesHandler(),
  YZMapUnmodifiablesHandler(),

  //Set
  YZSetHandler(),
  YZSetContainsHandler(),
  YZSetAddHandler(),
  YZSetAddAllHandler(),
  YZSetRemoveHandler(),
  YZSetLookupHandler(),
  YZSetRemoveALlHandler(),
  YZSetRetainALlHandler(),
  YZSetContainsAllHandler(),
  YZSetIntersectionAllHandler(),
  YZSetUnionHandler(),
  YZSetDifferenceHandler(),
  YZSetClearHandler(),
  YZSetToSetHandler(),
  YZSetElementAtHandler(),
  YZSetLengthHandler(),
  YZSetIsEmptyHandler(),
  YZSetIsNotEmptyHandler(),
  YZSetFirstHandler(),
  YZSetLastHandler(),
  YZSetFollowedByHandler(),
  YZSetJoinHandler(),
  YZSetToListHandler(),
  YZSetTakeHandler(),
  YZSetSkipHandler(),
  YZSetToStringHandler(),
  YZSetIteratorHandler(),
  YZSetFromHandler(),
  YZSetOfHandler(),
  YZSetIdentityHandler(),

  // Iterable
  YZIterableHandler(),
  YZIterableLengthHandler(),
  YZIterableIsEmptyHandler(),
  YZIterableIsNotEmptyHandler(),
  YZIterableFirstHandler(),
  YZIterableLastHandler(),
  YZIterableFollowedByHandler(),
  YZIterableContainsHandler(),
  YZIterableJoinHandler(),
  YZIterableToListHandler(),
  YZIterableToSetHandler(),
  YZIterableTakeHandler(),
  YZIterableSkipHandler(),
  YZIterableElementAtHandler(),
  YZIterableToStringHandler(),

  //control flow
  YZIfElseHandler(),
  YZSwitchCaseHandler(), 
  YZForLoopHandler(),
  YZWhileHandler(),

  //Sys
  YZBoolHandler(),
  YZSysBoolHandler(),
  YZSysBoolToStringHandler(),
  YZSysReturnHandler(),
  YZSysPrintHandler(),
  YZSysEqHandler(),
  YZSysNeqHandler(),
  YZSysGtHandler(),
  YZSysEgtHandler(),
  YZSysLtHandler(),
  YZSysEltHandler(),
  YZSysIsNullHandler(),
  YZSysInverterHandler(),
  YZSysAndHandler(),
  YZSysOrHandler(),

  // Math
  YZMathSqrtHandler(),
  YZMathExpHandler(),
  YZMathLogHandler(),
  YZMathMinHandler(),
  YZMathMaxHandler(),
  YZMathPowHandler(),
  YZMathSinHandler(),
  YZMathCosHandler(),
  YZMathTanHandler(),
  YZMathASinHandler(),
  YZMathACosHandler(),
  YZMathATanHandler(),
  YZMathATan2Handler(),
  YZMathEHandler(),
  YZMathLn10Handler(),
  YZMathLn2Handler(),
  YZMathLog2eHandler(),
  YZMathLog10eHandler(),
  YZMathPiHandler(),
  YZMathSqrt12Handler(),
  YZMathSqrt2Handler(),
];
